### PR TITLE
Kodair Client Update

### PR DESCRIPTION
**Pull request by ColeyHatt**
It's a client for Kodair written in PyQt5

### CODE REVIEW

**Comment by Farwalker3** [comment]
You'll have to explain this to me. What is PyQt5, and why do I need it? Also, please make pull requests to the nightly branch, not the main branch.

**Comment by ColeyHatt** [comment]
It is a python GUI module, and you don't really need it. If you install it you can see it's a web client wrapper for the site so if people want they can view the site through an app. It also looks cool as hell.
Screenshot 2024-04-28 072127

**Comment by Farwalker3** [comment]
What kind of operating systems can it run on, and is there a way to package it for an app store?

**Comment by ColeyHatt** [comment]
Linux, Mac and Windows, anything that can run Python it works great on. I think we can package it, would just need to know which App Store you want to put it on?

**Comment by Farwalker3** [comment]
If it works on Linux, Mac, and Windows. I would like to be able to package it for the Linux, Windows, and Mac app stores, respectively.

**Comment by ColeyHatt** [comment]
Packaged an installer for windows as well as a general use EXE. Cannot add here, check my distro.

**Comment by ColeyHatt** [comment]
https://github.com/ColeyHatt/kodair/releases/tag/Client

**Pull request merged**
